/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-15 13:48:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addPatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"/styles.css\"/>\n");
      out.write("  <title>Add Patient</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      out.write("  <h2 class=\"title\">Add New Patient</h2>\n");
      out.write("\n");
      out.write("  <form method=\"POST\" action=\"addPatient\">\n");
      out.write("    <table>\n");
      out.write("      <tr><td><label for=\"BIRTHDATE\">BIRTHDATE</label></td><td><input type=\"text\" name=\"BIRTHDATE\" id=\"BIRTHDATE\" placeholder=\"YYYY-MM-DD\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"DEATHDATE\">DEATHDATE</label></td><td><input type=\"text\" name=\"DEATHDATE\" id=\"DEATHDATE\" placeholder=\"YYYY-MM-DD (leave blank if living)\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"SSN\">SSN</label></td><td><input type=\"text\" name=\"SSN\" id=\"SSN\" placeholder=\"999-XX-XXXX\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"DRIVERS\">DRIVERS</label></td><td><input type=\"text\" name=\"DRIVERS\" id=\"DRIVERS\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"PASSPORT\">PASSPORT</label></td><td><input type=\"text\" name=\"PASSPORT\" id=\"PASSPORT\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"PREFIX\">PREFIX</label></td><td><input type=\"text\" name=\"PREFIX\" id=\"PREFIX\" placeholder=\"e.g. Mr., Mrs., Dr.\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"FIRST\">FIRST</label></td><td><input type=\"text\" name=\"FIRST\" id=\"FIRST\" placeholder=\"First name\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"LAST\">LAST</label></td><td><input type=\"text\" name=\"LAST\" id=\"LAST\" placeholder=\"Last name\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"SUFFIX\">SUFFIX</label></td><td><input type=\"text\" name=\"SUFFIX\" id=\"SUFFIX\" placeholder=\"e.g. Jr., III\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"MAIDEN\">MAIDEN</label></td><td><input type=\"text\" name=\"MAIDEN\" id=\"MAIDEN\" placeholder=\"If applicable\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"MARITAL\">MARITAL</label></td><td>\n");
      out.write("        <select name=\"MARITAL\" id=\"MARITAL\">\n");
      out.write("          <option value=\"\">—</option>\n");
      out.write("          <option value=\"M\">Married</option>\n");
      out.write("          <option value=\"S\">Single</option>\n");
      out.write("        </select>\n");
      out.write("      </td></tr>\n");
      out.write("      <tr><td><label for=\"RACE\">RACE</label></td><td><input type=\"text\" name=\"RACE\" id=\"RACE\" placeholder=\"e.g. white, black, asian\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"ETHNICITY\">ETHNICITY</label></td><td><input type=\"text\" name=\"ETHNICITY\" id=\"ETHNICITY\" placeholder=\"e.g. english, french\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"GENDER\">GENDER</label></td><td>\n");
      out.write("        <select name=\"GENDER\" id=\"GENDER\">\n");
      out.write("          <option value=\"\">—</option>\n");
      out.write("          <option value=\"M\">Male</option>\n");
      out.write("          <option value=\"F\">Female</option>\n");
      out.write("        </select>\n");
      out.write("      </td></tr>\n");
      out.write("      <tr><td><label for=\"BIRTHPLACE\">BIRTHPLACE</label></td><td><input type=\"text\" name=\"BIRTHPLACE\" id=\"BIRTHPLACE\" placeholder=\"City Country\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"ADDRESS\">ADDRESS</label></td><td><input type=\"text\" name=\"ADDRESS\" id=\"ADDRESS\" placeholder=\"Street address\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"CITY\">CITY</label></td><td><input type=\"text\" name=\"CITY\" id=\"CITY\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"STATE\">STATE</label></td><td><input type=\"text\" name=\"STATE\" id=\"STATE\"/></td></tr>\n");
      out.write("      <tr><td><label for=\"ZIP\">ZIP</label></td><td><input type=\"text\" name=\"ZIP\" id=\"ZIP\"/></td></tr>\n");
      out.write("    </table>\n");
      out.write("    <br/>\n");
      out.write("    <input type=\"submit\" value=\"Add Patient\" class=\"button-link\"/>\n");
      out.write("    <a href=\"patientList\" class=\"button-link\">Cancel</a>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
