/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-15 14:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;

public final class patientPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"/styles.css\"/>\n");
      out.write("  <title>Patient</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("  ");
 Map<String, String> patient = (Map<String, String>) request.getAttribute("patient");
     boolean isDeceased = false;
     if (patient != null) {
       isDeceased = patient.get("DEATHDATE") != null && !patient.get("DEATHDATE").isEmpty();
  
      out.write("\n");
      out.write("\n");
      out.write("  <h2 class=\"title\">Patient Details</h2>\n");
      out.write("\n");
      out.write("  <div>\n");
      out.write("    <a href=\"patientList\" class=\"button-link\">Back to Patient List</a>\n");
      out.write("    <a href=\"editPatient?id=");
      out.print( patient.get("ID") );
      out.write("\" class=\"button-link\">Edit</a>\n");
      out.write("    <form method=\"POST\" action=\"deletePatient\" style=\"display:inline;\"\n");
      out.write("        onsubmit=\"return confirm('Delete this patient? This cannot be undone.')\">\n");
      out.write("      <input type=\"hidden\" name=\"id\" value=\"");
      out.print( patient.get("ID") );
      out.write("\"/>\n");
      out.write("      <input type=\"submit\" value=\"Delete\"/>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <table>\n");
      out.write("    <tbody>\n");
      out.write("      <tr>\n");
      out.write("        <th>Name</th>\n");
      out.write("        <td>\n");
      out.write("          ");
 String prefixName = "";
             if (patient.get("PREFIX") != null && !patient.get("PREFIX").isEmpty()) {
               prefixName = patient.get("PREFIX") + " ";
             }
             String suffixName = "";
             if (patient.get("SUFFIX") != null && !patient.get("SUFFIX").isEmpty()) {
               suffixName = ", " + patient.get("SUFFIX");
             }
          
      out.write("\n");
      out.write("          ");
      out.print( prefixName );
      out.print( patient.get("FIRST") );
      out.write(' ');
      out.print( patient.get("LAST") );
      out.print( suffixName );
      out.write("\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("      ");
 String statusLabel;
         if (isDeceased) {
           statusLabel = "Deceased";
         } else {
           statusLabel = "Living";
         }
      
      out.write("\n");
      out.write("      <tr><th>Status</th><td>");
      out.print( statusLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String genderLabel = "";
         if (patient.get("GENDER") != null && !patient.get("GENDER").isEmpty()) {
           if ("M".equals(patient.get("GENDER"))) {
             genderLabel = "Male";
           } else {
             genderLabel = "Female";
           }
         }
      
      out.write("\n");
      out.write("      <tr><th>Gender</th><td>");
      out.print( genderLabel );
      out.write("</td></tr>\n");
      out.write("      <tr><th>Patient ID</th><td>");
      out.print( patient.get("ID") );
      out.write("</td></tr>\n");
      out.write("      ");
 String birthdateLabel = "";
         if (patient.get("BIRTHDATE") != null && !patient.get("BIRTHDATE").isEmpty()) {
           birthdateLabel = patient.get("BIRTHDATE");
         }
      
      out.write("\n");
      out.write("      <tr><th>Date of Birth</th><td>");
      out.print( birthdateLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String deathdateLabel = "";
         if (isDeceased) {
           deathdateLabel = patient.get("DEATHDATE");
         }
      
      out.write("\n");
      out.write("      <tr><th>Date of Death</th><td>");
      out.print( deathdateLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String birthplaceLabel = "";
         if (patient.get("BIRTHPLACE") != null && !patient.get("BIRTHPLACE").isEmpty()) {
           birthplaceLabel = patient.get("BIRTHPLACE");
         }
      
      out.write("\n");
      out.write("      <tr><th>Birthplace</th><td>");
      out.print( birthplaceLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String maritalLabel = "";
         if (patient.get("MARITAL") != null && !patient.get("MARITAL").isEmpty()) {
           maritalLabel = patient.get("MARITAL");
         }
      
      out.write("\n");
      out.write("      <tr><th>Marital Status</th><td>");
      out.print( maritalLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String raceLabel = "";
         if (patient.get("RACE") != null && !patient.get("RACE").isEmpty()) {
           raceLabel = patient.get("RACE");
         }
         String ethnicityLabel = "";
         if (patient.get("ETHNICITY") != null && !patient.get("ETHNICITY").isEmpty()) {
           ethnicityLabel = patient.get("ETHNICITY");
         }
         String raceEthnicitySeparator = "";
         if (!raceLabel.isEmpty() && !ethnicityLabel.isEmpty()) {
           raceEthnicitySeparator = " / ";
         }
      
      out.write("\n");
      out.write("      <tr><th>Race / Ethnicity</th><td>");
      out.print( raceLabel );
      out.print( raceEthnicitySeparator );
      out.print( ethnicityLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String maidenLabel = "";
         if (patient.get("MAIDEN") != null && !patient.get("MAIDEN").isEmpty()) {
           maidenLabel = patient.get("MAIDEN");
         }
      
      out.write("\n");
      out.write("      <tr><th>Maiden Name</th><td>");
      out.print( maidenLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String ssnLabel = "";
         if (patient.get("SSN") != null && !patient.get("SSN").isEmpty()) {
           ssnLabel = patient.get("SSN");
         }
      
      out.write("\n");
      out.write("      <tr><th>SSN</th><td>");
      out.print( ssnLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String passportLabel = "";
         if (patient.get("PASSPORT") != null && !patient.get("PASSPORT").isEmpty()) {
           passportLabel = patient.get("PASSPORT");
         }
      
      out.write("\n");
      out.write("      <tr><th>Passport</th><td>");
      out.print( passportLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String driversLabel = "";
         if (patient.get("DRIVERS") != null && !patient.get("DRIVERS").isEmpty()) {
           driversLabel = patient.get("DRIVERS");
         }
      
      out.write("\n");
      out.write("      <tr><th>Drivers License</th><td>");
      out.print( driversLabel );
      out.write("</td></tr>\n");
      out.write("      ");
 String addressLabel = "";
         if (patient.get("ADDRESS") != null && !patient.get("ADDRESS").isEmpty()) {
           addressLabel = patient.get("ADDRESS");
         }
         String cityLabel = "";
         if (patient.get("CITY") != null && !patient.get("CITY").isEmpty()) {
           cityLabel = ", " + patient.get("CITY");
         }
         String stateLabel = "";
         if (patient.get("STATE") != null && !patient.get("STATE").isEmpty()) {
           stateLabel = ", " + patient.get("STATE");
         }
         String zipLabel = "";
         if (patient.get("ZIP") != null && !patient.get("ZIP").isEmpty()) {
           zipLabel = " " + patient.get("ZIP");
         }
      
      out.write("\n");
      out.write("      <tr><th>Address</th><td>");
      out.print( addressLabel );
      out.print( cityLabel );
      out.print( stateLabel );
      out.print( zipLabel );
      out.write("</td></tr>\n");
      out.write("    </tbody>\n");
      out.write("  </table>\n");
      out.write("\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
