/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-15 14:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.net.URLEncoder;

public final class searchResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"/styles.css\"/>\n");
      out.write("  <title>Search Results</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      out.write("  <h2 class=\"title\">Search Results</h2>\n");
      out.write("  <a href=\"/search\" class=\"button-link\">New Search</a>\n");
      out.write("\n");
      out.write("  ");
 List<Map<String, String>> patients = (List<Map<String, String>>) request.getAttribute("result"); 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (patients != null && patients.size() > 0) { 
      out.write("\n");
      out.write("    <p><strong>");
      out.print( patients.size() );
      out.write("</strong> result(s) found</p>\n");
      out.write("    <table>\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          <th>Patient</th>\n");
      out.write("          <th>Date of Birth</th>\n");
      out.write("          <th>Gender</th>\n");
      out.write("          <th>City</th>\n");
      out.write("          <th>Status</th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("        ");

          for (Map<String, String> patient : patients) {
            String id        = (String) patient.get("ID");
            String firstName = (String) patient.get("FIRST");
            String lastName  = (String) patient.get("LAST");
            String gender    = (String) patient.get("GENDER");
            String birthDate = (String) patient.get("BIRTHDATE");
            String city      = (String) patient.get("CITY");
            String deathDate = (String) patient.get("DEATHDATE");
            boolean deceased = deathDate != null && !deathDate.isEmpty();
            String href      = "patientPage?id=" + URLEncoder.encode(id, "UTF-8");
        
      out.write("\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("            <a href=\"");
      out.print( href );
      out.write('"');
      out.write('>');
      out.print( firstName );
      out.write(' ');
      out.print( lastName );
      out.write("</a><br/>\n");
      out.write("            <small>");
      out.print( id );
      out.write("</small>\n");
      out.write("          </td>\n");
      out.write("          ");
 String birthDateDisplay = "––";
             if (birthDate != null && !birthDate.isEmpty()) {
               birthDateDisplay = birthDate;
             }
          
      out.write("\n");
      out.write("          <td>");
      out.print( birthDateDisplay );
      out.write("</td>\n");
      out.write("          ");
 String genderDisplay = "––";
             if (gender != null && !gender.isEmpty()) {
               if ("M".equals(gender)) {
                 genderDisplay = "Male";
               } else {
                 genderDisplay = "Female";
               }
             }
          
      out.write("\n");
      out.write("          <td>");
      out.print( genderDisplay );
      out.write("</td>\n");
      out.write("          ");
 String cityDisplay = "––";
             if (city != null && !city.isEmpty()) {
               cityDisplay = city;
             }
          
      out.write("\n");
      out.write("          <td>");
      out.print( cityDisplay );
      out.write("</td>\n");
      out.write("          ");
 String statusDisplay = "Living";
             if (deceased) {
               statusDisplay = "Deceased";
             }
          
      out.write("\n");
      out.write("          <td>");
      out.print( statusDisplay );
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  ");
 } else { 
      out.write("\n");
      out.write("    <p>No patients matched your search.</p>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
