/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-15 21:48:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;

public final class stats_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/styles.css\"/>\n");
      out.write("<title>Statistics</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      out.write("<h2 class=\"title\">Patient Statistics</h2>\n");
      out.write("<a href=\"saveJson\" class=\"button-link\">Save as JSON</a> ");
      out.write('\n');
      out.write('\n');

  Boolean savedJson = (Boolean) request.getAttribute("savedJson");
  if (Boolean.TRUE.equals(savedJson)) {

      out.write("\n");
      out.write("  <p class=\"success\">Data saved to data/patients.json</p> ");
      out.write('\n');
 } 
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"chart-grid\">\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("  <div class=\"chart-card\">\n");
      out.write("    <h3>Gender Distribution</h3>\n");
      out.write("    ");

      int male=(Integer) request.getAttribute("maleCount");
      int female=(Integer) request.getAttribute("femaleCount");
      int malePct=(Integer) request.getAttribute("malePct");
      int femalePct=(Integer) request.getAttribute("femalePct");
    
      out.write("\n");
      out.write("    <div class=\"pie-chart-wrapper\">\n");
      out.write("      <div class=\"pie-chart\" style=\"background: conic-gradient(#1976d2 0% ");
      out.print( malePct );
      out.write("%, #e91e8c ");
      out.print( malePct );
      out.write("% 100%)\"></div> ");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"chart-legend\">\n");
      out.write("      <span><div class=\"legend-color male-color\"></div> Male (");
      out.print( male );
      out.write(") — ");
      out.print( malePct );
      out.write("%</span>\n");
      out.write("      <span><div class=\"legend-color female-color\"></div> Female (");
      out.print( female );
      out.write(") — ");
      out.print( femalePct );
      out.write("%</span>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("  <div class=\"chart-card\">\n");
      out.write("    <h3>Age Distribution</h3>\n");
      out.write("    <div class=\"bar-chart-wrapper\">\n");
      out.write("      ");

        Map<String, Integer> ageGroups=(Map<String, Integer>) request.getAttribute("ageGroups");
        int maxCount=(Integer) request.getAttribute("maxCount"); // retrieve highest count for any age group
      
      out.write("\n");
      out.write("      <div class=\"bar-chart\">\n");
      out.write("        ");
 if (ageGroups != null && !ageGroups.isEmpty()) {
             for (Map.Entry<String, Integer> entry : ageGroups.entrySet()) {
               int val = entry.getValue();
               double barHeight = maxCount > 0 ? (val * 200.0 / maxCount) : 0; //bar height is scaled relative to the tallest bar
        
      out.write("\n");
      out.write("        <div class=\"bar-container\">\n");
      out.write("          <div class=\"bar-value\">");
      out.print( val );
      out.write("</div>\n");
      out.write("          <div class=\"bar\" style=\"height: ");
      out.print( String.format("%.0f", barHeight) );
      out.write("px\"></div> ");
      out.write("\n");
      out.write("          <div class=\"bar-label\">");
      out.print( entry.getKey() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("        ");
 } } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<h3>Patients by City</h3>\n");
      out.write("<table>\n");
      out.write("  <thead>\n");
      out.write("    <tr><th>City</th><th>Patients</th></tr>\n");
      out.write("  </thead>\n");
      out.write("  <tbody>\n");
      out.write("    ");

      Map<String, Integer> cityCount=(Map<String, Integer>) request.getAttribute("cityCount");
      if (cityCount != null) {
        for (Map.Entry<String, Integer> entry : cityCount.entrySet()) {
    
      out.write("\n");
      out.write("    <tr>\n");
      out.write("      <td>");
      out.print( entry.getKey() );
      out.write("</td>\n");
      out.write("      <td>");
      out.print( entry.getValue() );
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    ");
 } } 
      out.write("\n");
      out.write("  </tbody>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
